- README.md
- lgtm.yml
- package.json
> chore(readme): update info

- CHANGELOG.md
- __tests__/apis/$api.ts
- __tests__/index.spec.ts
- dev.ts
- lgtm.yml
- package-lock.json
- package.json
- src/buildRouteFile.ts
- src/cli.ts
- src/getConfig.ts
- src/template.ts
> chore(release): 0.1.1

- tsconfig.json
> fix(tsconfig): change target to es5

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): 0.1.2

- __tests__/apis/$api.ts
- __tests__/apis/v1/hoge/_hogeId/entries.json.ts
- src/buildRouteFile.ts
> feat(cli): correspond endpoint extension

- CHANGELOG.md
- __tests__/apis/$api.ts
- __tests__/apis/v1/hoge/_hogeId/entries.json.ts
- package-lock.json
- package.json
- src/buildRouteFile.ts
> chore(release): 0.3.0

- __tests__/apis/$api.ts
- src/buildRouteFile.ts
> fix(builder): add single quotes to property names

- CHANGELOG.md
- __tests__/apis/$api.ts
- package-lock.json
- package.json
- src/buildRouteFile.ts
> chore(release): 0.3.1

- __tests__/apis/$api.ts
- __tests__/apis/v1.1/2/_hogeId/test-4/_fugaId.ts
- __tests__/apis/v1.1/2/_hogeId/test-4/fuga aa.ts
- __tests__/apis/v1.1/2/_hogeId/test-4/index.ts
- __tests__/apis/v1.1/3.1.ts
- src/createMethodsString.ts
> feat(methods): determine question flag of config

- README.md
開発者向け情報として、ContributionセクションをREADMEに追記した。
併せて、開発者がローカルでビルドおよびwatchを行うための手順を追記した。
> aspida開発者がローカルでビルドを行うためのコマンドを、READMEに追記した

- .gitignore
- README.md
- examples/node/README.md
- examples/node/apis/@types.ts
- examples/node/apis/index.ts
- examples/node/apis/v1.1/2/_hogeId@HogeId/entries.json.ts
- examples/node/apis/v1.1/2/_hogeId@HogeId/test-4/_fugaId.ts
- examples/node/apis/v1.1/2/_hogeId@HogeId/test-4/fuga aa.ts
- examples/node/apis/v1.1/2/_hogeId@HogeId/test-4/index.ts
- examples/node/apis/v1.1/users/_userId@number.ts
- examples/node/package.json
- examples/node/src/index.ts
- examples/with-mock/README.md
- examples/with-mock/apis/@types.ts
- examples/with-mock/apis/index.ts
- examples/with-mock/apis/v1.1/2/_hogeId@HogeId/entries.json.ts
- examples/with-mock/apis/v1.1/2/_hogeId@HogeId/test-4/_fugaId.ts
- examples/with-mock/apis/v1.1/2/_hogeId@HogeId/test-4/fuga aa.ts
- examples/with-mock/apis/v1.1/2/_hogeId@HogeId/test-4/index.ts
- examples/with-mock/apis/v1.1/users/_userId@number.ts
- examples/with-mock/package.json
- examples/with-mock/src/index.ts
- src/createTemplateValues.ts
- tsconfig.json
> fix: ignore files other than ts

- __tests__/apis/$api.ts
- __tests__/apis/v2.0/index.ts
- src/createTemplateValues.ts
> fix: control the comma when index.ts is alone

- CHANGELOG.md
- README.md
- __tests__/apis/$api.ts
- __tests__/apis/v2.0/index.ts
- __tests__/utils/updateSnapshot.ts
- docs/ja/README.md
- examples/node/README.md
- jest.config.js
- package-lock.json
- package.json
- src/createTemplateValues.ts
> chore(release): 0.6.2

- package-lock.json
> fix: update modules

- README.md
- docs/ja/README.md
> chore: rewrite README

- .circleci/config.yml
- tsconfig.json
> chore: add typecheck

- packages/aspida/package.json
- packages/aspida/src/createMethodsString.ts
- yarn.lock
> refactor: use ts-morph

- .dependabot/config.yml
- packages/aspida-swagger/aspida.config.js
- packages/aspida-swagger/src/getConfig.ts
- packages/aspida-swagger/src/writeRouteFile.ts
- packages/aspida/README.md
- packages/aspida/__tests__/index.spec.ts
- packages/aspida/aspida.config.js
- packages/aspida/docs/ja/README.md
- packages/aspida/samples/$api.ts
- packages/aspida/src/buildTemplate.ts
- packages/aspida/src/cli.ts
- packages/aspida/src/cli/build.ts
- packages/aspida/src/getConfig.ts
> feat: add baseURL to config

- packages/aspida/__tests__/index.spec.ts
> chore(aspida): add writing test

- README.md
- packages/aspida-axios/README.md
- packages/aspida-fetch/README.md
- packages/aspida-ky/README.md
- packages/aspida/README.md
- packages/aspida/docs/ja/README.md
> chore: update logos of readme

- .dependabot/config.yml
> chore: set target branch

- packages/aspida-axios/package.json
- packages/aspida-axios/src/index.ts
- packages/aspida-mock/README.md
- packages/aspida-mock/package.json
> fix(aspida-mock): fix baseURL and release v0.2.3

- packages/pathpida/package.json
> chore(pathpida): fix and release v0.0.1

- packages/pathpida/$path.ts
- packages/pathpida/__tests__/index.spec.ts
- packages/pathpida/package.json
- packages/pathpida/samples/_userId/test.ts
- packages/pathpida/samples/index.tsx
- packages/pathpida/src/createMethodsString.ts
- packages/pathpida/src/createTemplateValues.ts
- packages/pathpida/src/listFiles.ts
> feat(pathpida): delete question from query

- CHANGELOG.md
- packages/aspida/package.json
- packages/aspida/src/createTemplateValues.ts
- packages/aspida/src/getConfig.ts
- packages/aspida/src/index.ts
- packages/pathpida/$path.ts
- packages/pathpida/README.md
- packages/pathpida/__tests__/index.spec.ts
- packages/pathpida/aspida.config.js
- packages/pathpida/package.json
- packages/pathpida/pathpida.config.js
- packages/pathpida/src/buildTemplate.ts
- packages/pathpida/src/createTemplateValues.ts
- packages/pathpida/src/getConfig.ts
> chore(release): 0.12.1

- packages/pathpida/package.json
- packages/pathpida/src/buildTemplate.ts
- packages/pathpida/src/dataToURLString.ts
> chore(pathpida): fix bug and release v0.2.1

- packages/aspida/src/createMethodsString.ts
- packages/aspida/src/createTemplateValues.ts
> refactor(aspida): optimize processing of ts-morph

- CHANGELOG.md
- package.json
- packages/aspida-axios/package.json
- packages/aspida-fetch/package.json
- packages/aspida-ky/package.json
- packages/aspida/package.json
- packages/aspida/src/createMethodsString.ts
- packages/aspida/src/createTemplateValues.ts
- packages/pathpida/package.json
- yarn.lock
> chore(release): 0.14.1

- package.json
- packages/aspida/package.json
- packages/aspida/src/createMethodsString.ts
- packages/aspida/src/createTemplateValues.ts
- packages/aspida/src/parseInterface.ts
- yarn.lock
> refactor(aspida): delete ts-morph

- CHANGELOG.md
- package.json
- packages/aspida-axios/package.json
- packages/aspida-fetch/package.json
- packages/aspida-ky/package.json
- packages/aspida/package.json
- packages/aspida/src/createMethodsString.ts
- packages/aspida/src/createTemplateValues.ts
- packages/aspida/src/parseInterface.ts
- packages/openapi2aspida/README.md
- packages/openapi2aspida/package.json
- packages/pathpida/package.json
- yarn.lock
> chore(release): 0.14.2

- packages/aspida/samples/$api.ts
- packages/aspida/samples/index.ts
- packages/aspida/src/parseInterface.ts
> fix(aspida): add test case

- CHANGELOG.md
- packages/aspida-axios/package.json
- packages/aspida-fetch/package.json
- packages/aspida-ky/package.json
- packages/aspida/package.json
- packages/aspida/samples/$api.ts
- packages/aspida/samples/index.ts
- packages/aspida/src/parseInterface.ts
- packages/openapi2aspida/package.json
- packages/pathpida/package.json
> chore(release): 0.14.3

- CHANGELOG.md
- packages/aspida-axios/package.json
- packages/aspida-fetch/package.json
- packages/aspida-ky/package.json
- packages/aspida/package.json
- packages/aspida/samples/index.ts
- packages/aspida/src/parseInterface.ts
- packages/openapi2aspida/package.json
> chore(release): 0.14.5

- .prettierrc
- package.json
- packages/aspida-fetch/index.ts
- packages/aspida-mock/src/cli/buildRouteFile.ts
- packages/aspida-mock/src/types.ts
- yarn.lock
> chore: update prettier 2.0

- packages/aspida-mock/package.json
- packages/aspida-mock/src/utils.ts
> fix(mock): parse path values

- package.json
- packages/aspida-mock/package.json
- packages/aspida-mock/src/utils.ts
- packages/aspida/README.md
- packages/aspida/src/createMethodsString.ts
- packages/openapi2aspida/package.json
- packages/openapi2aspida/src/buildV3.ts
- packages/openapi2aspida/src/builderUtils/converters.ts
- yarn.lock
> chore: fix typo of README

- packages/aspida/src/createTemplateValues.ts
- packages/openapi2aspida/aspida.config.js
- packages/openapi2aspida/samples/simple.yaml
- packages/openapi2aspida/samples/simple/$api.ts
- packages/openapi2aspida/samples/simple/dummy/_id/content.ts
- packages/openapi2aspida/samples/simple/dummy/_id/query.ts
- packages/openapi2aspida/samples/simple/dummy/_id/simple.ts
- packages/openapi2aspida/samples/swagger/$api.ts
- packages/openapi2aspida/samples/swagger/store/inventory.ts
- packages/openapi2aspida/samples/swagger/store/order/_orderId.ts
- packages/openapi2aspida/samples/swagger/user/_username.ts
- packages/openapi2aspida/samples/swagger/user/logout.ts
- packages/openapi2aspida/src/buildTemplate.ts
- packages/openapi2aspida/src/buildV3.ts
> fix(openapi): output of endpoints without props

- packages/aspida-mock/src/utils.ts
> fix(mock): detect if resBody is pojo when copying

- CHANGELOG.md
- package.json
- packages/aspida-axios/package.json
- packages/aspida-fetch/package.json
- packages/aspida-ky/package.json
- packages/aspida-mock/package.json
- packages/aspida-mock/src/utils.ts
- packages/aspida-node-fetch/package.json
- packages/aspida/package.json
- packages/aspida/src/createTemplateValues.ts
- packages/openapi2aspida/aspida.config.js
- packages/openapi2aspida/package.json
- packages/openapi2aspida/samples/simple.yaml
- packages/openapi2aspida/samples/simple/$api.ts
- packages/openapi2aspida/samples/simple/dummy/_id/content.ts
- packages/openapi2aspida/samples/simple/dummy/_id/query.ts
- packages/openapi2aspida/samples/simple/dummy/_id/simple.ts
- packages/openapi2aspida/samples/swagger/$api.ts
- packages/openapi2aspida/samples/swagger/store/inventory.ts
- packages/openapi2aspida/samples/swagger/store/order/_orderId.ts
- packages/openapi2aspida/samples/swagger/user/_username.ts
- packages/openapi2aspida/samples/swagger/user/logout.ts
- packages/openapi2aspida/src/buildTemplate.ts
- packages/openapi2aspida/src/buildV3.ts
- yarn.lock
>  chore(release): 0.15.1

- packages/openapi2aspida/samples/swagger/$api.ts
- packages/openapi2aspida/samples/swagger/store/inventory.ts
- packages/openapi2aspida/src/builderUtils/converters.ts
- packages/openapi2aspida/src/builderUtils/methods2MockString.ts
> fix(openapi): support additionalProperties

- package.json
- packages/aspida-server/LICENSE
- packages/aspida-server/apis/$controllers.ts
- packages/aspida-server/apis/$server.ts
- packages/aspida-server/apis/@controller.ts
- packages/aspida-server/apis/@middleware.ts
- packages/aspida-server/apis/index.ts
- packages/aspida-server/apis/user/$values.ts
- packages/aspida-server/apis/user/@controller.ts
- packages/aspida-server/apis/user/@user.ts
- packages/aspida-server/apis/user/_userId@number/$values.ts
- packages/aspida-server/apis/user/_userId@number/@controller.ts
- packages/aspida-server/apis/user/_userId@number/index.ts
- packages/aspida-server/apis/user/index.ts
- packages/aspida-server/aspida.config.js
- packages/aspida-server/bin/index.js
- packages/aspida-server/package.json
- packages/aspida-server/src/build.ts
- packages/aspida-server/src/buildRouteFile.ts
- packages/aspida-server/src/cli.ts
- packages/aspida-server/src/createRouteString.ts
- packages/aspida-server/src/getConfig.ts
- packages/aspida-server/src/index.ts
- packages/aspida-server/src/writeRouteFile.ts
- packages/aspida-server/tsconfig.build.json
- yarn.lock
> feat(server): add prototype

- packages/openapi2aspida/samples/simple.yaml
- packages/openapi2aspida/samples/simple/$api.ts
- packages/openapi2aspida/samples/simple/user/_id@number.ts
- packages/openapi2aspida/src/buildV3.ts
- packages/openapi2aspida/src/builderUtils/getDirName.ts
> fix(openapi): support paths common parameters

- package.json
- packages/aspida-server/__test__/index.spec.ts
- packages/aspida-server/apis/@controller.ts
- packages/aspida-server/apis/index.ts
- yarn.lock
> refactor(server): remove form-data types

- packages/openapi2aspida/src/builderUtils/resolvers.ts
> fix(openapi): for lint of typescript v3.9

- packages/aspida/src/cli/version.ts
- packages/pathpida/src/cli/version.ts
> fix: required path of version command

- CHANGELOG.md
- packages/aspida-axios/package.json
- packages/aspida-axios/src/index.ts
- packages/aspida-fetch/package.json
- packages/aspida-ky/index.ts
- packages/aspida-ky/package.json
- packages/aspida-node-fetch/package.json
- packages/aspida/__tests__/clients.spec.ts
- packages/aspida/package.json
- packages/aspida/sample1/$api.ts
- packages/aspida/sample2/$api.ts
- packages/aspida/sample2/v1.1/$api.ts
- packages/aspida/sample2/v1.1/2/$api.ts
- packages/aspida/src/createTemplateValues.ts
> chore(release): 0.19.1

- CHANGELOG.md
- packages/aspida-axios/package.json
- packages/aspida-fetch/package.json
- packages/aspida-ky/package.json
- packages/aspida-node-fetch/package.json
- packages/aspida/package.json
- packages/aspida/sample1/$api.ts
- packages/aspida/sample2/$api.ts
- packages/aspida/sample2/v1.1/$api.ts
- packages/aspida/sample2/v1.1/2/$api.ts
- packages/aspida/sample2/v1.1/3.1/$api.ts
- packages/aspida/sample2/v1.1/users/$api.ts
- packages/aspida/sample2/v2.0/$api.ts
- packages/aspida/src/buildTemplate.ts
- packages/aspida/src/createMethodsString.ts
- packages/aspida/src/createTemplateValues.ts
> chore(release): 0.19.2

- CHANGELOG.md
- README.md
- packages/aspida-axios/package.json
- packages/aspida-fetch/package.json
- packages/aspida-ky/package.json
- packages/aspida-node-fetch/package.json
- packages/aspida/README.md
- packages/aspida/docs/ja/README.md
- packages/aspida/package.json
- packages/aspida/sample1/$api.ts
- packages/aspida/sample2/$api.ts
- packages/aspida/sample2/v1.1/$api.ts
- packages/aspida/sample2/v1.1/3.1/$api.ts
- packages/aspida/sample2/v2.0/$api.ts
- packages/aspida/src/createTemplateValues.ts
> chore(release): 0.19.3

- CHANGELOG.md
- README.md
- package.json
- packages/aspida-axios/package.json
- packages/aspida-fetch/package.json
- packages/aspida-ky/package.json
- packages/aspida-node-fetch/package.json
- packages/aspida/README.md
- packages/aspida/docs/ja/README.md
- packages/aspida/package.json
- packages/aspida/sample1/v1.1/2/_hogeId@HogeId/test-4/_fugaId.ts
- packages/aspida/sample2/v1.1/2/_hogeId@HogeId/test-4/_fugaId.ts
- packages/aspida/src/getConfig.ts
- packages/aspida/src/parseInterface.ts
- yarn.lock
> chore(release): 0.19.4

- CHANGELOG.md
- README.md
- packages/aspida-axios/README.md
- packages/aspida-axios/package.json
- packages/aspida-fetch/README.md
- packages/aspida-fetch/package.json
- packages/aspida-ky/README.md
- packages/aspida-ky/package.json
- packages/aspida-mock/README.md
- packages/aspida-mock/docs/ja/README.md
- packages/aspida-mock/package.json
- packages/aspida-node-fetch/README.md
- packages/aspida-node-fetch/package.json
- packages/aspida/README.md
- packages/aspida/docs/ja/README.md
- packages/aspida/package.json
> change aspidajs to aspida

- packages/aspida-axios/package.json
- packages/aspida-mock/package.json
> release: aspida-axios@0.9.5

- CHANGELOG.md
- README.md
- package.json
- packages/aspida-axios/package.json
- packages/aspida-fetch/package.json
- packages/aspida-ky/package.json
- packages/aspida-mock/__tests__/lib/index.spec.ts
- packages/aspida-mock/src/cli/index.ts
- packages/aspida-node-fetch/package.json
- packages/aspida/README.md
- packages/aspida/__tests__/index.spec.ts
- packages/aspida/docs/ja/README.md
- packages/aspida/package.json
- packages/aspida/src/cli.ts
- packages/aspida/src/commands.ts
- tsconfig.json
- yarn.lock
> chore(release): 0.20.1

- CHANGELOG.md
- README.md
- packages/aspida-axios/package.json
- packages/aspida-fetch/package.json
- packages/aspida-ky/package.json
- packages/aspida-mock/__tests__/lib/index.spec.ts
- packages/aspida-mock/src/cli/index.ts
- packages/aspida-node-fetch/package.json
- packages/aspida/README.md
- packages/aspida/__tests__/index.spec.ts
- packages/aspida/docs/ja/README.md
- packages/aspida/package.json
- packages/aspida/src/cli.ts
- packages/aspida/src/commands.ts
> chore(release): 0.20.2

- CHANGELOG.md
- package.json
- packages/aspida-axios/package.json
- packages/aspida-fetch/package.json
- packages/aspida-ky/package.json
- packages/aspida-node-fetch/package.json
- packages/aspida-swr/package.json
- packages/aspida-swrv/package.json
- packages/aspida/package.json
- packages/aspida/src/index.ts
- yarn.lock
> chore(release): 0.21.1

- CHANGELOG.md
- packages/aspida-axios/package.json
- packages/aspida-fetch/package.json
- packages/aspida-ky/package.json
- packages/aspida-node-fetch/package.json
- packages/aspida-swr/package.json
- packages/aspida-swrv/package.json
- packages/aspida/package.json
- packages/aspida/sample1/$api.ts
- packages/aspida/sample2/$api.ts
- packages/aspida/sample2/v1.1/$api.ts
- packages/aspida/sample2/v1.1/2/$api.ts
- packages/aspida/sample2/v1.1/3.1/$api.ts
- packages/aspida/sample2/v1.1/users/$api.ts
- packages/aspida/sample2/v2.0/$api.ts
- packages/aspida/src/createMethodsString.ts
> chore(release): 0.21.3

- .github/workflows/nodejs.yml
- CHANGELOG.md
- package.json
- packages/aspida-axios/package.json
- packages/aspida-fetch/package.json
- packages/aspida-node-fetch/package.json
- packages/aspida-react-query/package.json
- packages/aspida-swr/package.json
- packages/aspida-swrv/package.json
- packages/aspida/package.json
- packages/aspida/sample1/$api.ts
- packages/aspida/sample1/foo%3Abar/_bar_id@string.json.ts
- packages/aspida/sample2/$api.ts
- packages/aspida/sample2/foo%3Abar/$api.ts
- packages/aspida/sample2/foo%3Abar/_bar_id@string.json.ts
- packages/aspida/src/createTemplateValues.ts
> chore(release): 1.2.1

- CHANGELOG.md
- packages/aspida-axios/package.json
- packages/aspida-fetch/index.ts
- packages/aspida-fetch/package.json
- packages/aspida-node-fetch/index.ts
- packages/aspida-node-fetch/package.json
- packages/aspida-react-query/package.json
- packages/aspida-swr/package.json
- packages/aspida-swrv/package.json
- packages/aspida/package.json
> chore(release): 1.4.1

- packages/aspida-fetch/index.ts
- packages/aspida-node-fetch/index.ts
export type FetchConfig
Since `FetchConfig` is used in multiple places, I declare it as a variable. That's why I want Type.
```
type FetchConfig = RequestInit & {
baseURL?: string;
throwHttpErrors?: boolean;
};
const baseUrl = process.env.BASE_URL as string;
export const myAspidaFetchConfig: FetchConfig = {
baseURL: baseUrl,
throwHttpErrors: true,
credentials: "include",
mode: "cors",
headers: {
"Content-Type": "application/json; charset=utf-8",
},
};
```
> Export FetchConfig Type

- CHANGELOG.md
- packages/aspida-axios/package.json
- packages/aspida-fetch/package.json
- packages/aspida-node-fetch/package.json
- packages/aspida-react-query/package.json
- packages/aspida-swr/package.json
- packages/aspida-swrv/package.json
- packages/aspida/package.json
- yarn.lock
> chore(release): 1.6.1

- CHANGELOG.md
- packages/aspida-axios/package.json
- packages/aspida-fetch/package.json
- packages/aspida-node-fetch/package.json
- packages/aspida-react-query/package.json
- packages/aspida-swr/package.json
- packages/aspida-swrv/package.json
- packages/aspida/package.json
- packages/aspida/src/getDirentTree.ts
> chore(release): 1.6.3

- packages/aspida-swr/index.ts
- changed from deprecated types to recommended types in `useAspidaSWR`
- `responseInterface` -> `SWRResponse`
- `ConfigInterface` -> `SWRConfiguration`
- minor code cleanup
> refactor(aspida-swr): fix to avoid using deprecated types

- packages/aspida/docs/ja/README.md
> [improve] improve translation and translated of untranslated parts

- .github/pull_request_template.md
- .github/workflows/nodejs.yml
- .github/workflows/release-drafter-main.yml
- resolves #
- resolves #
- ...
> ci: update release and fix typo

- .github/workflows/release-drafter-main.yml
- resolves #
- resolves #
- ...
> ci: update to use GITHUB_TOKEN for PR target events

- .github/workflows/nodejs.yml
- package.json
- yarn.lock
- resolves #
- resolves #
- ...
> ci: typo fix

- .github/workflows/release-drafter-auto-labeler.yml
- .github/workflows/release-drafter-main.yml
- resolves #
- resolves #
- ...
auto-labelerだけ使いたいがその機能がdraft-releaserにないため一旦統一する。
そうしないと大量のdraft releaseができてしまう。
> ci: update

- packages/aspida-swrv/index.ts
- resolves #
- resolves #
- ...
> revert(swrv): merge 1.7.1

- packages/aspida-swr/index.ts
- packages/aspida-swrv/index.ts
- resolves #
- resolves #https://github.com/aspida/aspida/issues/700
- ...
https://github.com/aspida/aspida/issues/682
https://github.com/aspida/aspida/issues/700
> feat(swr/swrv): new option key and fetcher

- packages/aspida-swr/index.ts
- packages/aspida-swrv/index.ts
- resolves #
- resolves https://github.com/aspida/aspida/issues/731
- ...
> feat: function to get default key

- packages/aspida/samples/aliasOnly/$api.ts
- packages/aspida/samples/aliasOnly/foo%3Abar/$api.ts
- packages/aspida/samples/aliasOnly/v1.1/$api.ts
- packages/aspida/samples/aliasOnly/v1.1/2/$api.ts
- packages/aspida/samples/aliasOnly/v1.1/3.1/$api.ts
- packages/aspida/samples/aliasOnly/v1.1/users/$api.ts
- packages/aspida/samples/aliasOnly/v2.0/$api.ts
- packages/aspida/samples/basic/$api.ts
- packages/aspida/samples/eachDir/$api.ts
- packages/aspida/samples/eachDir/foo%3Abar/$api.ts
- packages/aspida/samples/eachDir/v1.1/$api.ts
- packages/aspida/samples/eachDir/v1.1/2/$api.ts
- packages/aspida/samples/eachDir/v1.1/3.1/$api.ts
- packages/aspida/samples/eachDir/v1.1/users/$api.ts
- packages/aspida/samples/eachDir/v2.0/$api.ts
- packages/aspida/samples/normalOnly/$api.ts
- packages/aspida/src/createMethodsString.ts
- resolves #
- resolves https://github.com/aspida/aspida/issues/688
- ...
> feat: add "or undefined" explicitly to support exactOptionalPropertyTypes

- packages/aspida/aspida.config.js
- packages/aspida/samples/useDefineMethods/$api.ts
- packages/aspida/samples/useDefineMethods/_sampleId@number.json.ts
- packages/aspida/samples/useDefineMethods/foo%3Abar/_bar_id@string.json.ts
- packages/aspida/samples/useDefineMethods/foo%3Abar/_fooId@number%40create.ts
- packages/aspida/samples/useDefineMethods/foo%3Abar/index.ts
- packages/aspida/samples/useDefineMethods/index.ts
- packages/aspida/samples/useDefineMethods/polymorphism/users/_userId/index.ts
- packages/aspida/samples/useDefineMethods/polymorphism/users/index.ts
- packages/aspida/samples/useDefineMethods/v1.1.ts
- packages/aspida/samples/useDefineMethods/v1.1/2/_hogeId.ts
- packages/aspida/samples/useDefineMethods/v1.1/2/_hogeId@number.ts
- packages/aspida/samples/useDefineMethods/v1.1/2/_hogeId@string/entries.json.ts
- packages/aspida/samples/useDefineMethods/v1.1/2/_hogeId@string/test-4/_fugaId.ts
- packages/aspida/samples/useDefineMethods/v1.1/2/_hogeId@string/test-4/fuga aa.ts
- packages/aspida/samples/useDefineMethods/v1.1/2/_hogeId@string/test-4/index.ts
- packages/aspida/samples/useDefineMethods/v1.1/3.1.ts
- packages/aspida/samples/useDefineMethods/v1.1/_articleId.json.ts
- packages/aspida/samples/useDefineMethods/v1.1/users/_userId@string.ts
- packages/aspida/samples/useDefineMethods/v2.0/index.ts
- packages/aspida/src/index.ts
- packages/aspida/src/parseInterface.ts
Issue Number: https://github.com/aspida/aspida/issues/686
Implemented the features introduced in the following post
https://zenn.dev/yutaro_elk/articles/c65052449a6212
update parser RegExp rule for support following code style. 
(but not support type analysis. If want to implement code analysis, [ts-type-parser](https://github.com/MrMaxie/ts-types-parser) may be useful.)
```tsx
export Methods = DefineMethods<{
get: {
resBody: string
}
}>
```
it help  type-checking & code completion by tsserver.
usages:
```tsx
import { DefineMethos } from 'aspida'
export Methods = DefineMethods<{
get: {
resBody: string
}
}>
```
> Add methods definition helper type

- packages/aspida/src/index.ts
- resolves #
- resolves #
- ...
> revert: just revert exported type of AspidaMethodParams and AspidaMethods

- packages/aspida/samples/basic/$api.ts
- packages/aspida/samples/basic/polymorphism/get/index.ts
- packages/aspida/samples/useDefineMethods/$api.ts
- packages/aspida/src/createMethodsString.ts
resolves https://github.com/aspida/aspida/issues/689
- resolves #
- resolves #
- ...
> fix: check resBody even if reqBody is absent

- packages/aspida/package.json
- yarn.lock
- resolves #
- resolves #
- ...
> fix: update minimist and chokidar

- packages/aspida-fetch/README.md
- packages/aspida-fetch/__tests__/index.spec.ts
- packages/aspida-fetch/index.ts
- packages/aspida-fetch/package.json
- packages/aspida-node-fetch/README.md
- packages/aspida-node-fetch/__tests__/index.spec.ts
- packages/aspida-node-fetch/index.ts
- packages/aspida-node-fetch/package.json
- packages/aspida/aspida.config.js
- packages/aspida/samples/array/$api.ts
- packages/aspida/samples/array/users/index.ts
- yarn.lock
- resolves #
- resolves #775
- `@aspida-fetch` および `@asipda-node-fetch` のconfigに `paramsSerializer`を追加
> add  fetch config

- README.md
- jest.config.ts
- packages/aspida-axios/src/mockClient.ts
- packages/aspida/src/getDirentTree.ts
- packages/aspida/src/index.ts
- packages/aspida/src/parseInterface.ts
- tsconfig.json
- resolves #
- resolves #
- ...
> feat: support exactOptionalPropertyTypes

- packages/aspida-axios/package.json
- packages/aspida-node-fetch/package.json
- packages/aspida-react-query/package.json
- packages/aspida-swr/package.json
- packages/aspida-swrv/package.json
- packages/aspida/package.json
- resolves #
- resolves #
- ...
> release v1.13.1

- package-lock.json
- packages/aspida-axios/package.json
- packages/aspida-fetch/package.json
- packages/aspida-node-fetch/package.json
- packages/aspida-react-query/package.json
- packages/aspida-swr/package.json
- packages/aspida-swrv/package.json
- resolves #802
- resolves #
- ...
> fix: remove unused bin property
